name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: "check"
    runs-on: ubuntu-latest
    steps:
      - run: |
        ./ty check . --output-format github
